### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by ihoru** [befelix/nautilus-pushbullet#1]
I have this error message in output:

> Traceback (most recent call last):
>   File "/usr/share/nautilus-python/extensions/nautilus-pushbullet.py", line 79, in push
>     success, file_data = self.upload_file(tmp, os.path.basename(f))
> ValueError: too many values to unpack

I am using ubuntu-mate. I run nautilus from terminal and copy output from there.

**Comment by befelix** [comment]
Yep, looks like the API of the pushbullet library changed. Could you confirm that it's working again now?
Thanks,
Felix

**Comment by ihoru** [comment]
Sorry, I've installed another extension already...
